### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by hadifarnoud** [pda/pheanstalk#127]
I get this error once in a while. I have no connection issue with the server nor is there any firewall issue.

the queue works just fine but every 24 hours it gives me Pheanstalk_Exception_ConnectionException error

vendor/pda/pheanstalk/classes/Pheanstalk/Socket/NativeSocket.php:35
Socket error 110: Connection timed out (connecting to 10.179.196.25:11300)

I don't even know how to debug this issue.

**Comment by ndixita** [comment]
Was this resolved?

**Comment by pda** [comment]
That's a network timeout connecting to port 11300 on the beanstalkd server. It's happening outside Pheanstalk — actually in the socket API and/or TCP stack in the kernel I believe.

The only way it relates to Pheanstalk is how long the timeout is set to. [Pheanstalk defaults to two seconds](https://github.com/pda/pheanstalk/blob/f095be7568f3438cd5e4d1e59016857bbcb869b1/src/Connection.php#L18) and you can change that by passing the third arg to `Pheanstalk`:

```php
$connectTimeout = 10; // seconds
$p = new Pheanstalk($host, $port, $connectTimeout);
```

However generally if you haven't connected in two seconds, something is terribly wrong; if anything you might want to _reduce_ the default timeout.

**Comment by MiteshShah** [comment]
@pda Same issue for me

I was able to `telnet 127.0.0.1 11300` but Pheanstalk say timeout.
I'd change $connectTimeout = 20 but still same issue 

```
[2016-07-04 03:35:35] prod.ERROR: exception 'Pheanstalk\Exception\ConnectionException' with message 'Socket error 110: Connection timed out (connecting to 127.0.0.1:11300)' in /home/cronrunner/jobs/prod/vendor/pda/pheanstalk/src/Socket/NativeSocket.php:45
Stack trace:
#0 /home/cronrunner/jobs/prod/vendor/pda/pheanstalk/src/Connection.php(195): Pheanstalk\Socket\NativeSocket->__construct('127.0.0.1', 11300, 20, false)
#1 /home/cronrunner/jobs/prod/vendor/pda/pheanstalk/src/Connection.php(101): Pheanstalk\Connection->_getSocket()
```

**Comment by MiteshShah** [comment]
@pda You are right the issue was on TCP network buffer.
I'd increase the buffer limit and everything works great!

Refer - https://miteshshah.github.io/linux/centos/how-to-fix-nf_conntrack-table-full-dropping-packet/

Might be this one help other users so posting here.

**Comment by dikdust** [comment]
I think that @MiteshShah solution in the new version is not sufficient. I'll have some

[DATE] mautic.CRITICAL: Uncaught PHP Exception Pheanstalk\Exception
\ConnectionException: "Socket error 110: Connection timed out (connecting to localhost:11300)" at /path/to/mautic/vendor/pda/pheanstalk/src/Socket/NativeSocket.php line 45 {"exception":"[object] (Pheanstalk\\Exception\\ConnectionException(code: 0): Socket error 110: Connection timed out (connecting to localhost:11300) at /path/to/mautic/vendor/pda/pheanstalk/src/Socket/NativeSocket.php:45)"} []

and after a few of this mautic seems to crash. Is better to try RabbitMQ instead of beanstalkd?

I have 4Gb ram on server, and cron is:


0,15,30,45 * * * * sudo -u www-data /usr/bin/php /path/to/mautic/app/console mautic:segments:update #mautic-segments-cron
5,20,35,50 * * * * sudo -u www-data /usr/bin/php /path/to/mautic/app/console mautic:campaigns:update #mautic-campaings-update-cron
10,25,40,55 * * * * sudo -u www-data /usr/bin/php /path/to/mautic/app/console mautic:campaigns:trigger #mautic-campaigns-trigger-cron
*/7 * * * * sudo -u www-data /usr/bin/php /path/to/mautic/app/console mautic:emails:send #mautic-email-send-cron
*/21 * * * * sudo -u www-data /usr/bin/php /path/to/mautic/app/console mautic:email:fetch #mautic-email-send-cron

Don't know if the crash is related but I haven't other issues in logs ...

**Comment by SamMousa** [comment]
> and after a few of this mautic seems to crash. Is better to try RabbitMQ instead of beanstalkd?

I think that won't help. The problem is in your TCP stack as explained earlier in the previous post. 
The exception you see actually has nothing to do with PHP or Beanstalk.
