### ISSUE TITLE
delete error

### ISSUE THREAD

**Issue by fucongcong** [pda/pheanstalk#133]
watch testjob1

WATCHING 2
reserve-with-timeout 10

TIMED_OUT
watch testjob2

WATCHING 3
reserve-with-timeout 10

RESERVED 1 12
delete 1

NOT_FOUND
PHP Fatal error:  Uncaught exception 'Pheanstalk\Exception\ServerException' with message 'Cannot delete job 1: NOT_FOUND' in /private/var/www/Group/vendor/pda/pheanstalk/src/Command/DeleteCommand.php:44
Stack trace:
#0 /private/var/www/Group/vendor/pda/pheanstalk/src/Connection.php(143): Pheanstalk\Command\DeleteCommand->parseResponse('NOT_FOUND', NULL)
#1 /private/var/www/Group/vendor/pda/pheanstalk/src/Pheanstalk.php(396): Pheanstalk\Connection->dispatchCommand(Object(Pheanstalk\Command\DeleteCommand))
#2 /private/var/www/Group/vendor/pda/pheanstalk/src/Pheanstalk.php(68): Pheanstalk\Pheanstalk->_dispatch(Object(Pheanstalk\Command\DeleteCommand))
#3 /private/var/www/Group/core/Group/Queue/Bear.php(137): Pheanstalk\Pheanstalk->delete(Object(Pheanstalk\Job))
#4 [internal function]: Group\Queue\Bear->Group\Queue\{closure}(9)
#5 /private/var/www/Group/core/Group/Queue/Bear.php(121): swoole_process->start()
#6 /private/var/www/Group/core/Group/Queue/Bear.php(41): Group\Queue\Bear->startWorkers()
#7 /private/var/www/Group/core/Gro in /private/var/www/Group/vendor/pda/pheanstalk/src/Command/DeleteCommand.php on line 44

you see jobId = 1 is exist but delete failed.

**Comment by fucongcong** [comment]
I found the resaon. it can not delete on asnyc

**Comment by fucongcong** [comment]
when I open two process to get the job I find the return error.
The reason is that the two processes are different tube wtach，when a process reserve ,the response is the other process wtach's response.so the jobId is error.

**Comment by rohanpande** [comment]
@pda Thank you for this library, @fucongcong I also faced this issue here is what I did to solve my issue. 

In order to delete a scheduled/queued job you have to first do peek as it return job object present in the queue and then you can delete it. If Job is not present in the queue it's throws NOT_FOUND exception which you can handle by applying try-catch box 

`				
try {
  $job = $pheanstalk->peek($jobId);
  $pheanstalk->delete($job);
} catch (\Exception $e) {
  // handled missing Beanstalkd job from the tube
}

`
This is just incase if someone came along looking for solution.
