### ISSUE TITLE
putInTube switching default tube.

### ISSUE THREAD

**Issue by SamMousa** [pda/pheanstalk#142]
When using putInTube, the current tube for the connection is switched. This is a side-effect that is not ideal.

Consider the scenario:
1. I have a connection to beanstalk.
2. I have set the tube to use to "this-is-my-default" 
3. I call `$pheanstalk->put(...)` and as expected it puts it in the default tube listed above.
4. I call `$pheanstalk->putInTube("some-tube", ...)` and as expected it puts it in the tube passed as first argument.
5. I call `$pheanstalk->put(...)` and it puts it in the `some-tube` tube listed above.

Since the beanstalk connection might be passed around throughout the application how can I ever make sure the default is not inadvertently changed by someone using `putInTube`?

In my opinion `useTube()` should change the connection state, but `putInTube()` should not.

**Comment by frickenate** [comment]
This one is a little awkward. `putInTube()` could be made to reuse the previously used tube after inserting the job. However:

1. If an exception is thrown while trying to reuse the previous tube, developers are left to handle the difference between "an exception was thrown before the job could be inserted (ie: real failure), vs. "the job was successfully inserted, but an exception was thrown trying to reset tube state". Most developers would not understand that this distinction even exists, leading to scenarios where a job is being treated as not inserted even when it was.

2. Developers using `putInTube` inside a loop to batch insert many jobs into a single queue would be performing a ridiculous number of round trips to the server if the queue being inserted to is different than the previously selected one. Example: `$queue->useTube('A'); foreach (range(1, 100) as $id) { $queue->putInTube('B', $id); }`. That code would do 300 commands instead of 101. It would take an ugly internal tracking hack to prevent those unnecessary commands.

If you are in a position to find `putInTube` a hazard, you should simply not use it. You could go one step further on a team project and extend the `Pheanstalk\Pheanstalk` class to throw an exception from `putInTube` to explicitly forbid its use.

**Comment by SamMousa** [comment]
I think having a side effect is worse than having 2 exceptions... Exceptions are explicit and must be handled; side effects are implicit and will create hard to track down bugs.

**Comment by SamMousa** [comment]
I still agree with my own idea...

Requirements for an implementation:
1. Must not switch tubes excessively.
2. Must not switch tubes needlessly.
3. Must support persistent connections.

**Comment by SamMousa** [comment]
I just noticed that these functions also change state:
- `peekReady`
- `peekBuried`
- `peekDelayed`

This means that either we patch all of these and make the code more complicated, or we simply remove the functionality to dynamically switch tubes.

We could offer something like `withTube(string $tube, \Closure $closure)` if we really need it.
Could could then look like this:
```php
$pheanstalk->withTube('other', function(Pheanstalk $p) {
    $p->peekBuried();
    $p->put($x);
}

```
Instead of this:
```php
$tube = $pheanstalk->listTubeUsed();
try {
    $pheanstalk->useTube('other');
    $pheanstalk->put($job);
} finally {
    $pheanstalk->useTube($tube);
}
```

@frickenate what do you think?

**Comment by SamMousa** [comment]
@dmcfaul what's your opinion? You mentioned you use it pretty extensively.

My goal for v4 is to modernize the library using PHP typehinting; also I want to get rid of all side-effects.
